apiVersion: v1
kind: Service
metadata:
  name: leak-dns
  namespace: kube-system
spec:
  externalTrafficPolicy: Local
  internalTrafficPolicy: Local
  ports:
  - name: dns
    nodePort: 5300
    port: 53
    protocol: UDP
  selector:
    k8s-app: kube-dns
  type: NodePort